### ISSUE TITLE
Incorrect/Update Information Required for `Abhishek Rajesh`

### ISSUE THREAD

**Issue by AbhishekR03** [0xsrmist/Main-Website#78]
## What is the issue about?

Abhishek Rajesh's information is incorrect/needs to be updated...

## What Information needs to be updated or corrected?

Issue with the image

## Internal Usage [DO NOT DELETE]

- Profile Slug: `abhishek-rajesh`

**Comment by kunalkeshan** [comment]
Hey @AbhishekR03, thanks for updating here. 
Can you share a 1:1 cropped ratio of the section of the image that you want to display on the website?

Feel free to attach the image as part of this issue!

**Comment by AbhishekR03** [comment]
![IMG_20231114_162135_053-1 Cropped](https://github.com/0xsrmist/Main-Website/assets/109751680/ded016d5-6d78-4c7f-9bb7-949633279000)

Here's the image with 1:1 crop

**Comment by kunalkeshan** [comment]
Awesome! Can you check and see if it's alright now - https://0xsrmist.xyz/team/abhishek-rajesh ?
