### ISSUE TITLE
Incorrect/Update Information Required for `Yash Garg`

### ISSUE THREAD

**Issue by yashgarg32** [0xsrmist/Main-Website#81]
## What is the issue about?

Yash Garg's information is incorrect/needs to be updated...

## Internal Usage [DO NOT DELETE]
Actually i updated wrong twitter id can you please just correct it 
https://twitter.com/yashgarg_18
- Profile Slug: `yash-garg`

**Comment by kunalkeshan** [comment]
Hey @yashgarg32, it's updated on the website. Can you give it a look and if it's alright feel free to close this issue?

**Comment by kunalkeshan** [comment]
![image](https://github.com/0xsrmist/Main-Website/assets/68579547/fc268dcd-1ec4-40ac-8655-51105c86d862)

Link works - Check bottom left
