### ISSUE TITLE
Incorrect/Update Information Required for Astitva Veer Garg

### ISSUE THREAD

**Issue by astitvaveergarg** [0xsrmist/Main-Website#82]
### What is the issue about?
Astitva Veer Garg's information is incorrect/needs to be updated...

### What Information needs to be updated or corrected?
Issue with the image

### Internal Usage [DO NOT DELETE]
Profile Slug: astitva-veer-garg

Attached: 1:1 Cropped Profile Image
![Astitva](https://github.com/0xsrmist/Main-Website/assets/91984568/0b8db0de-5291-415f-94cf-432b093fc138)

**Comment by kunalkeshan** [comment]
Hey @astitvaveergarg 👋, the picture is updated. Do give it a look. If it's alright, feel free to close this issue.

**Comment by kunalkeshan** [comment]
Image updated reflected on website -> check -> https://0xsrmist.xyz/team/astitva-veer-garg
