### ISSUE TITLE
Profile missing for "Samarth Mishra" entirely

### ISSUE THREAD

**Issue by FUTHARVSTUD** [0xsrmist/Main-Website#83]
**What is the issue about?**
- "Samarth Mishra" profile is missing.

**What Information needs to be updated or corrected?**

- My profile needs to be added to the team page

**Internal Usage [DO NOT DELETE]**

- Profile Slug: samarth-mishra

- Member of: Technical domain

- Branch: CSE(Core)

- 1:1 cropped photo
![20231217_131826.jpg](https://github.com/0xsrmist/Main-Website/assets/122509056/b858b856-e2df-4342-917c-c6cc37437187)

- Description:
I am majoring in Computer Science and thriving on my enthusiasm for Python and machine learning. Currently, I'm contributing to front-end development, where I merge my technical skills with a passion for innovation. My driving force is the fervor to empower the underserved and elevate lives through impactful software solutions.

- Github: https://www.github.com/FUTHARVSTUD
- Instagram: https://www.instagram.com/samarth_.mishra/
- LinkedIn: https://www.linkedin.com/in/samarth20mishra
- Mail: sm2713@srmist.edu.in

**Comment by kunalkeshan** [comment]
Hey @FUTHARVSTUD 👋, the page has been created. 

Check it out here 👉 https://0xsrmist.xyz/team/samarth-mishra

If there are any changes, do inform us in the same issue. 
If not, feel free to close this issue.
