### ISSUE TITLE
Incorrect/Update Information Required for `N GANESHKUMAR`

### ISSUE THREAD

**Issue by Ganesh5757** [0xsrmist/Main-Website#86]
## What is the issue about?

N GANESHKUMAR's information is incorrect/needs to be updated...

## What Information needs to be updated or corrected?
In the profile links are missing (i.e) Instagram,Github,LinkedIn,mail,etc.

## Internal Usage [DO NOT DELETE]

- Profile Slug: `n-ganeshkumar`

**Comment by kunalkeshan** [comment]
Hey @Ganesh5757, the details have been updated 👉 https://0xsrmist.xyz/team/n-ganeshkumar

If everything is alright feel free to close this issue as completed.
